# Change these first
owner: digiquip # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Kvipp
    url: https://kvipp.it
  - name: DigiQuip Registry
    url: https://registry.kvipp.io
  - name: DigiQuip Main Service
    url: https://demo.digiquip.com/
  - name: DigiQuip Website
    url: https://digiquip.no
  - name: DigiQuip PIM
    url: https://pim.digiquip.com
  - name: DigiQuip Translation
    url: https://translate.digiquip.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kvipp.io
  # baseUrl: /your-repo-name
  theme: light
  logoUrl: https://digiquip.no/img/logo.svg
  name: DQ Service Status
  introTitle: "**Our main services** are constantly monitored for response time and downtime."
  introMessage: Check in for current status, scheduled maintenance or incident alerts. Based on the excelent [Upptime open source project](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
